// Pure TypeScript PDF 1.4 Document Generator for Cogniva Academic Reports

export interface PdfReportColumn {
  header: string;
  key: string;
  width?: number;
}

export interface PdfReportData {
  title: string;
  subtitle?: string;
  department?: string;
  section?: string;
  subject?: string;
  facultyName?: string;
  facultyEmail?: string;
  academicYear?: string;
  semester?: string;
  generatedAt?: string;
  columns: PdfReportColumn[];
  rows: Record<string, any>[];
  summaryText?: string;
}

// Escapes special characters for PDF literal strings () \
function escapePdfText(text: string): string {
  if (!text) return '';
  return String(text)
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/[^\x20-\x7E]/g, ''); // Keep printable ASCII
}

export function generateAcademicPdfReport(data: PdfReportData): {
  blob: Blob;
  dataUrl: string;
  filename: string;
} {
  const timestamp = data.generatedAt || new Date().toLocaleString();
  const dateStamp = new Date().toISOString().split('T')[0];
  
  // Format deterministic filename
  const cleanSubject = (data.subject || 'Academic').replace(/[^a-zA-Z0-9]/g, '_');
  const cleanTitle = (data.title || 'Report').replace(/[^a-zA-Z0-9]/g, '_');
  const cleanSection = (data.section || 'All').replace(/[^a-zA-Z0-9]/g, '_');
  const filename = `Cogniva_${cleanSubject}_${cleanTitle}_${cleanSection}_${dateStamp}.pdf`;

  // PDF Page Setup (A4: 595.28 x 841.89 points)
  const pageWidth = 595;
  const pageHeight = 842;
  const marginX = 40;
  const startY = 790;

  let streamContent = '';

  // Helper to add commands
  const add = (cmd: string) => {
    streamContent += cmd + '\n';
  };

  // Header Background Banner
  add('0.06 0.09 0.16 rg'); // Deep slate blue #0F172A
  add(`0 770 ${pageWidth} 72 re f`);

  // Brand Header Text
  add('BT');
  add('/F2 16 Tf');
  add('1.0 1.0 1.0 rg');
  add(`40 818 Td (${escapePdfText('COGNIVA')} - ${escapePdfText('ACADEMIC INTELLIGENCE PLATFORM')}) Tj`);
  add('ET');

  add('BT');
  add('/F1 9 Tf');
  add('0.7 0.8 0.95 rg');
  add('40 798 Td (OFFICIAL FACULTY ACADEMIC REPORT | CONFIDENTIAL) Tj');
  add('ET');

  // Report Title Box
  add('0.97 0.98 1.0 rg');
  add(`40 705 ${pageWidth - 80} 55 re f`);
  add('0.8 0.85 0.95 RG');
  add('1 w');
  add(`40 705 ${pageWidth - 80} 55 re S`);

  add('BT');
  add('/F2 14 Tf');
  add('0.1 0.15 0.3 rg');
  add(`55 742 Td (${escapePdfText(data.title.toUpperCase())}) Tj`);
  add('ET');

  if (data.subtitle) {
    add('BT');
    add('/F1 9 Tf');
    add('0.3 0.35 0.45 rg');
    add(`55 720 Td (${escapePdfText(data.subtitle)}) Tj`);
    add('ET');
  }

  // Metadata Grid Box
  const metaY = 635;
  add('0.96 0.96 0.97 rg');
  add(`40 ${metaY} ${pageWidth - 80} 60 re f`);
  add('0.85 0.85 0.88 RG');
  add(`40 ${metaY} ${pageWidth - 80} 60 re S`);

  add('BT');
  add('/F2 9 Tf');
  add('0.2 0.2 0.25 rg');
  add(`50 ${metaY + 42} Td (Department: ${escapePdfText(data.department || 'CSE')}) Tj`);
  add(`200 0 Td (Section: ${escapePdfText(data.section || 'CSE-C')}) Tj`);
  add(`160 0 Td (Subject: ${escapePdfText(data.subject || 'All Courses')}) Tj`);
  add('ET');

  add('BT');
  add('/F1 9 Tf');
  add('0.3 0.3 0.35 rg');
  add(`50 ${metaY + 22} Td (Generated By: ${escapePdfText(data.facultyName || 'Dr. Anjali Menon')}) Tj`);
  add(`200 0 Td (Academic Year: 2025-2026) Tj`);
  add(`160 0 Td (Generated On: ${escapePdfText(timestamp)}) Tj`);
  add('ET');

  // Summary Banner
  if (data.summaryText) {
    add('0.93 0.97 1.0 rg');
    add(`40 595 ${pageWidth - 80} 30 re f`);
    add('0.3 0.5 0.8 RG');
    add(`40 595 ${pageWidth - 80} 30 re S`);

    add('BT');
    add('/F2 9 Tf');
    add('0.1 0.3 0.6 rg');
    add(`50 606 Td (Summary: ${escapePdfText(data.summaryText)}) Tj`);
    add('ET');
  }

  // Table Setup
  const tableTopY = data.summaryText ? 570 : 610;
  const colCount = data.columns.length;
  const availableWidth = pageWidth - 80;
  const colWidth = Math.floor(availableWidth / Math.max(1, colCount));

  // Table Header Fill
  add('0.15 0.23 0.38 rg'); // Dark Navy Header
  add(`40 ${tableTopY - 24} ${availableWidth} 24 re f`);

  // Table Header Text
  add('BT');
  add('/F2 9 Tf');
  add('1.0 1.0 1.0 rg');

  let currentX = 50;
  data.columns.forEach((col) => {
    add(`${currentX} ${tableTopY - 16} Td (${escapePdfText(col.header.toUpperCase())}) Tj`);
    add(`${-currentX} ${-(tableTopY - 16)} Td`); // Reset text matrix
  });
  add('ET');

  // Table Rows
  let rowY = tableTopY - 24;
  const rowHeight = 22;

  data.rows.forEach((row, idx) => {
    rowY -= rowHeight;

    // Alternate Row Shading
    if (idx % 2 === 0) {
      add('0.98 0.98 0.99 rg');
      add(`40 ${rowY} ${availableWidth} ${rowHeight} re f`);
    }

    // Row Border
    add('0.9 0.9 0.92 RG');
    add(`40 ${rowY} ${availableWidth} ${rowHeight} re S`);

    // Row Cell Texts
    add('BT');
    add('/F1 8.5 Tf');
    add('0.15 0.15 0.2 rg');

    currentX = 50;
    data.columns.forEach((col) => {
      let rawVal = row[col.key];
      if (rawVal === undefined || rawVal === null) rawVal = '-';
      const cellText = escapePdfText(String(rawVal));

      add(`${currentX} ${rowY + 6} Td (${cellText}) Tj`);
      add(`${-currentX} ${-(rowY + 6)} Td`);
    });
    add('ET');
  });

  // Footer Page Number & Disclaimer
  add('0.85 0.85 0.88 RG');
  add('40 50 515 0 m 555 50 l S'); // Horizontal Line

  add('BT');
  add('/F1 8 Tf');
  add('0.4 0.4 0.45 rg');
  add(`40 35 Td (${escapePdfText('Cogniva Academic Intelligence System • Generated via Faculty Copilot')}) Tj`);
  add('ET');

  add('BT');
  add('/F2 8 Tf');
  add('0.3 0.3 0.35 rg');
  add(`490 35 Td (${escapePdfText('Page 1 of 1')}) Tj`);
  add('ET');

  // Construct PDF Objects
  const pdfObjects: string[] = [];

  // Object 1: Catalog
  pdfObjects.push('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj');

  // Object 2: Pages
  pdfObjects.push('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj');

  // Object 3: Page Definition
  pdfObjects.push('3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>\nendobj');

  // Object 4: Font Helvetica
  pdfObjects.push('4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj');

  // Object 5: Font Helvetica-Bold
  pdfObjects.push('5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj');

  // Object 6: Stream Contents
  pdfObjects.push(`6 0 obj\n<< /Length ${streamContent.length} >>\nstream\n${streamContent}endstream\nendobj`);

  // Build PDF File
  let pdfString = '%PDF-1.4\n';
  const offsets: number[] = [0];

  pdfObjects.forEach((obj) => {
    offsets.push(pdfString.length);
    pdfString += obj + '\n';
  });

  // Cross-reference table (xref)
  const xrefStart = pdfString.length;
  pdfString += `xref\n0 ${pdfObjects.length + 1}\n0000000000 65535 f \n`;

  for (let i = 1; i <= pdfObjects.length; i++) {
    const off = offsets[i].toString().padStart(10, '0');
    pdfString += `${off} 00000 n \n`;
  }

  // Trailer
  pdfString += `trailer\n<< /Size ${pdfObjects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;

  const blob = new Blob([pdfString], { type: 'application/pdf' });
  const dataUrl = URL.createObjectURL(blob);

  return { blob, dataUrl, filename };
}
